SET TERMOUT On
SET ECHO On

GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO khcc IDENTIFIED BY final ;
ALTER USER KHCC DEFAULT TABLESPACE USERS;
ALTER USER KHCC TEMPORARY TABLESPACE TEMP;
CONNECT khcc/final


DROP TABLE CARPOOL;
DROP TABLE REPORTS;
DROP TABLE COMMENTS;
DROP TABLE REVIEW_BOARD;
DROP TABLE QA_BOARD;
DROP TABLE RESERVATION;
DROP TABLE CAR;
DROP TABLE ZONE;
DROP TABLE MEMBER;


CREATE TABLE MEMBER(
	M_EMAIL		VARCHAR2(100) PRIMARY KEY,
	M_PASSWORD	VARCHAR2(100) NOT NULL,
	M_NAME		VARCHAR2(100) NOT NULL,
	M_BIRTH		VARCHAR2(100) NOT NULL,
	m_phone		VARCHAR2(100) NOT NULL,
	M_ZIPCODE1  VARCHAR2(100),
	M_ZIPCODE2  VARCHAR2(100),
	M_ADDR1  	VARCHAR2(100),
	M_ADDR2  	VARCHAR2(100),
	M_DRIVERCODE	VARCHAR2(100),
	M_COUPON	VARCHAR2(100),
	M_POINT		NUMBER,
	M_DRIVER	NUMBER DEFAULT 0,
	M_ACCOUNT	VARCHAR2(100)
);

drop table member;
select * from member;

update member set M_ZIPCODE1 = '111', M_ZIPCODE2 = '222', M_ADDR1 = '용인시 수지구', M_ADDR2 = '상현동' where M_EMAIL = 'khcc@nate.com'

create table zipcode (
	no number PRIMARY KEY,
	ZIPCODE varchar2(7),
	sido varchar2(10),
	gugun varchar2(20),
	dong varchar2(50),
	bunji varchar2(50)
);

-- ZONE, CAR, RESERVATION 카쉐어링 관련 테이블 (실시간 예약)
CREATE TABLE ZONE(
	Z_PLACE		VARCHAR2(100) PRIMARY KEY,
	Z_LATITUDE	NUMBER(9,6) NOT NULL,
	Z_LONGITUDE	NUMBER(9,6) NOT NULL
);

CREATE TABLE CAR(
	C_ID		VARCHAR2(100) PRIMARY KEY,
	C_KIND		VARCHAR2(100) NOT NULL,
	C_MODEL		VARCHAR2(100) NOT NULL,
	C_RENTFEE	NUMBER NOT NULL,
	C_OILFEE	NUMBER NOT NULL,
	C_IMG		VARCHAR2(100) NOT NULL,
	C_PLACE		VARCHAR2(100) NOT NULL,
	C_START		DATE,
	C_END		DATE,
	C_STATE		NUMBER DEFAULT 0,
	FOREIGN KEY(C_PLACE) REFERENCES ZONE(Z_PLACE)
);

CREATE TABLE RESERVATION(
	RES_ID		VARCHAR2(100) NOT NULL,
	RES_CARID	VARCHAR2(100) NOT NULL,
	RES_TOTAL	NUMBER NOT NULL,
	FOREIGN KEY(RES_CARID) REFERENCES CAR(C_ID)
);

CREATE TABLE QA_BOARD(
	Q_NUM		NUMBER PRIMARY KEY,
	Q_ID		VARCHAR2(100) NOT NULL,
	Q_SUBJECT	VARCHAR2(300) NOT NULL,
	Q_CONTENT	VARCHAR2(4000) NOT NULL,
	Q_RE_REF	NUMBER,
	Q_RE_LEV	NUMBER,
	Q_RE_SEQ	NUMBER,
	Q_READCOUNT	NUMBER DEFAULT 0,
	Q_DATE		DATE DEFAULT SYSDATE
);

DELETE SEQUENCE QA_NUM_SEQ;

CREATE SEQUENCE QA_NUM_SEQ
	INCREMENT BY 1
	START WITH 1 NOCACHE;

CREATE TABLE REVIEW_BOARD(
	RB_NUM		NUMBER PRIMARY KEY,
	RB_ID		VARCHAR2(100) NOT NULL,
	RB_SUBJECT	VARCHAR2(300) NOT NULL,
	RB_CONTENT	VARCHAR2(4000) NOT NULL,
	RB_SCORE	NUMBER NOT NULL,
	RB_IMG		VARCHAR2(100),
	RB_DATE		DATE DEFAULT SYSDATE,
	RB_CATEGORY	VARCHAR2(100)
);

DELETE SEQUENCE RB_NUM_SEQ;

CREATE SEQUENCE RB_NUM_SEQ
	INCREMENT BY 1
	START WITH 1 NOCACHE;

CREATE TABLE COMMENTS(
	C_NUM		NUMBER PRIMARY KEY,
	C_ID		VARCHAR2(50) NOT NULL,
	C_CONTENT	VARCHAR2(1000) NOT NULL,
	C_REF		NUMBER,
	C_DATE		DATE DEFAULT SYSDATE,
	FOREIGN KEY(C_REF) REFERENCES REVIEW_BOARD(RB_NUM)
);

DELETE SEQUENCE COMM_NUM_SEQ;

CREATE SEQUENCE COMM_NUM_SEQ
	INCREMENT BY 1
	START WITH 1 NOCACHE;

CREATE TABLE REPORTS(
	R_NUM		NUMBER PRIMARY KEY,
	R_SENDER	VARCHAR2(100) NOT NULL,
	R_RECEIVER	VARCHAR2(100) DEFAULT 'admin',
	R_SUBJECT	VARCHAR2(300) NOT NULL,
	R_CONTENT	VARCHAR2(4000) NOT NULL,
	R_DATE		DATE DEFAULT SYSDATE,
	R_ILLEGALID	VARCHAR2(100) NOT NULL,
	R_IMG		VARCHAR2(100) NOT NULL
);

DELETE SEQUENCE REP_NUM_SEQ;

CREATE SEQUENCE REP_NUM_SEQ
	INCREMENT BY 1
	START WITH 1 NOCACHE;

CREATE TABLE CARPOOL(
	CP_NUM		NUMBER PRIMARY KEY,
	CP_ID		VARCHAR2(100) NOT NULL,
	CP_DEPART	VARCHAR2(100) NOT NULL,
	CP_ARRIVE	VARCHAR2(100) NOT NULL,
	CP_TIME		DATE NOT NULL,
	CP_SUM		NUMBER NOT NULL
);

DELETE SEQUENCE CP_NUM_SEQ;

CREATE SEQUENCE CP_NUM_SEQ
	INCREMENT BY 1
	START WITH 1 NOCACHE;		

COMMIT;

SET TERMOUT ON
SET ECHO ON